In [5]:
# Numpy ia s python lib used for numerical and scientific computing. it provides support for arrays, matrices and many mathmatical function.

In [6]:
!pip install numpy

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 6, 7, 8])
print(arr)

[1 2 3 4 6 7 8]


In [8]:
#2. array creation
# arrays in numpty are called ndarray.you can create arrays from lists or use functions to generate them
a = np.array([1, 2, 3])  # 1D array
b = np.array([[1, 2], ['sri', 'trainer']])  #2D
print(b)

[['1' '2']
 ['sri' 'trainer']]


In [9]:
# 3. Array attributes
#   np. array object have attribute like  shape, size, ndim and dtype that describe the arraya
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])
print("Array:|n", arr)

Array:|n [[1 2 3]
 [4 5 6]
 [7 8 8]]


In [10]:
print("Shape:", arr.shape) # rows and colums
print("Size:", arr.size)  # count/len
print("Dimensions:", arr.ndim)
print("Data Types:", arr.dtype)

Shape: (3, 3)
Size: 9
Dimensions: 2
Data Types: int64


In [11]:
#4, array indexing and slicing
# numpy supports powerful slicing and indexing for accessing data element
arr = np.array([[10, 20, 30], [40, 50, 60]]) # indexing array accessing element by their index position
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
a = np.array([10, 20, 30, 40])
print(a[1:3])

[20 30]


In [13]:
print("Element at [0:1]:", arr[0, 1]) # rows, colums
print("First row:", arr[0])
print("First colum:", arr[:, 0])

Element at [0:1]: 20
First row: [10 20 30]
First colum: [10 40]


In [14]:
#slicing arrays 
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print("arr[1:2]:", arr[1:4])
print("arr[:3]:", arr[:3]) #equvalent to arr[0:3]
print("arr[::2]:", arr[::2])

[10 20 30 40 50]
arr[1:2]: [20 30 40]
arr[:3]: [10 20 30]
arr[::2]: [10 30 50]


In [15]:
# 5. Array Data Types( you can specify the data type of element in a numpy array using the dtype parameter)
a = np.array([1.0, 2.0], dtype='int32')
print(a.dtype)


int32


In [16]:
a

array([1, 2], dtype=int32)

In [17]:
#6, Reshaping arrays  (use reshape() to change tha shape of an array without changing its data)
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a)

[1 2 3 4 5 6 7 8]


In [18]:
b = a.reshape(4,2)
print(b)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
#7, array operation (numpy supports element wise operation such as addition, subtraction, multiplication, and division)
a = np.array([1, 2])
b = np.array([3, 4])
print(a+b)

[4 6]


In [20]:
# 8 Broadcasting  (allows numpy to perfrom operation on arrays of diffrent shapes
a = np.array([1, 3, 6])
b = 2
print(a*b)


[ 2  6 12]


In [21]:
# 9. uneversial function( numpy provides fast element wise operation called ufuncs like np.sqrt(), np.exp()etc)
a = np.array([1, 4, 9])
print(np.exp(a))

[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [22]:
np.sqrt(a)


array([1., 2., 3.])

In [23]:
#10, random module
rand_nums = np.random.randint(1,10, size=(2,3)) # 2 rows 3 colums
print(rand_nums)

[[4 5 8]
 [2 6 8]]


In [24]:
#ADVANCED NUMPY
#11, Boolean indexing ( filter array element using boolean condition)
a = np.array([10, 20, 30, 40, 21, 20.5])
print(a[a >-30])


[10.  20.  30.  40.  21.  20.5]


In [25]:
#12 Aggregation function (functions like sum, mean, std, min, max help summarize array data)
arr = np.array([1, 2, 3])
print("Max:", arr.max())
print("Min:", arr.min())
print("Sum:", arr.sum())
print("Mean:", arr.mean())
print("Std Dev:", arr.std())

Max: 3
Min: 1
Sum: 6
Mean: 2.0
Std Dev: 0.816496580927726


In [26]:
#13, Axis operation  (perform operation along specific axes)
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [27]:
print(a.sum(axis=0)) # sum along 0-colums 1-rows

[4 6]


In [28]:
#14, Linear Algebra( it includes linear algebra function such as dot, inv, eig,etc)
a = np.array([[1, 2], [3, 4]])  # det(a)=ad-bc
a


array([[1, 2],
       [3, 4]])

In [29]:
print(np.linalg.inv(a))  # Inverse of matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


In [30]:
# 15, Memory Efficiency: Views vs Copies ( views share the same memory as the original array, while copies have independent memory)
a = np.array([1, 2, 4])
a


array([1, 2, 4])

In [31]:
b = a.view()
b

array([1, 2, 4])

In [32]:
c = a.copy()
c

array([1, 2, 4])

In [33]:
a[0] = 99
print(b[0], c[0])

99 1


In [34]:
# numpy , array creation, properties, and operations
# np.zeros() → array of 0s
# np.ones()  → array of 1s
# np.empty() → uninitialized values
# np.full()  → array filled with chosen value

In [35]:
# numpy linspace
# returns evenly spaced numbers over a specified interval
import numpy as np
arr = np.linspace(0, 10, 5)
print("linspace(0, 10, 5):", arr)

linspace(0, 10, 5): [ 0.   2.5  5.   7.5 10. ]


In [36]:
# numpy. arange
# returns evenly spaced values within a given interval
arr = np.arange(1, 10, 2)
print("arange(1, 10, 2):", arr)

arange(1, 10, 2): [1 3 5 7 9]


In [37]:
# numpy.random.randint
# generate random integers between low and high
arr = np.random.randint(0, 12, size=(3, 4))
print("random.randint(0, 10, size=(3,2)):\n", arr)

random.randint(0, 10, size=(3,2)):
 [[10  0 10 10]
 [ 5  5  1  0]
 [ 5  9  8  9]]


In [38]:
#numpy.zeros
# creates an array filled with ones
arr = np.ones((2, 3))
print("ones((2, 3)):\n", arr)

ones((2, 3)):
 [[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
#numpy .empty
# create an array without initalizing its values
arr = np.zeros((2, 3))
print("zeros((2, 3))\n", arr)

zeros((2, 3))
 [[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
# numpy .full
# create an array filled with a constant values
arr = np.full((2, 3), 7)
print("full((2, 3), 7):\n", arr)

full((2, 3), 7):
 [[7 7 7]
 [7 7 7]]


In [41]:
# arithmetic operations
# perform element -wise operation on array
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Array a:", a)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Array a: [1 2 3]
Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [44]:
# Concatenating Arrays
# Combine multiple arrays 
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [8, 9]])
concat = np.concatenate((a, b), axis=1)
print("Concatenated:\n", concat)

Concatenated:
 [[1 2 5 6]
 [3 4 8 9]]


In [45]:
# flattening arrays
# convert a multi-dimensions arrray inti 1d array
arr = np.array([[1, 2], [3, 4]])
arr
flat = arr.flatten()
print("Flattend", flat)

Flattend [1 2 3 4]


In [47]:
# Iterating Through arrays
# looping through element of a multi-dimension

arr = np.array([[1, 2], [3, 4]])
for row in arr:
    for i in row:
        print(i, end=' ')

1 2 3 4 